## Gradient descent 

In [180]:
data  = np.loadtxt("_training_boston_x_y_train.csv",delimiter=",")

In [181]:
data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [182]:
df = pd.DataFrame(data,columns = ["0","1","2","3","4","5","6","7","8","9","10","11","12","13"])

In [183]:
df.head()

0         1         2         3         4         5         6  \
0 -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1 -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2  0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3  0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4 -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   

          7         8         9        10        11        12    13  
0 -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1  0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2 -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3 -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4  0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5

In [184]:
df.head()

0         1         2         3         4         5         6  \
0 -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1 -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2  0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3  0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4 -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   

          7         8         9        10        11        12    13  
0 -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1  0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2 -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3 -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4  0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5

In [185]:
df

0         1         2         3         4         5         6  \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

            7         8         9        10        11        12    13  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5  
..        ...       ...       ...       ...       ...       ...   ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  50.0  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  14.3  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  20.8  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  22.6  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  50.0  

[379 rows x 14 columns]

In [186]:
points = np.array(df.drop("13",axis=1))

In [187]:
points.shape


(379, 13)

In [188]:
def step_gradient(points, learning_rate, m,c):
    m_slope = np.zeros(13)
    c_slope = 0
    M=len(points)
    for i in range(len(points)):
        x = points[i]
        y = np.array(df["13"])[i]
        for j in range(13):
            m_slope[j] = m_slope[j]-(2/M)* (y - (m * x).sum() )*x[j]
            
            
    for j in range(13):
        m[j] = m[j] - learning_rate*m_slope[j]
        c_slope = c_slope + (-2/M)* (y - (m * x).sum() )
    c = c -learning_rate*c_slope
    return m,c


In [189]:
def gradient_descent(points, learning_rate, num_iterations):
    m=np.zeros(13)
    c = 0
    for i in range(num_iterations):
        m ,c= step_gradient(points, learning_rate, m,c)
    return m,c

In [190]:
def costfunction(points, m):
    cost = 0
    M = len(points)
    for i in range(M):
        x = points[i]
        y = df["13"][i]
        cost += (1/M)*((y - (m*x).sum() )**2)
    return cost


In [392]:
def run():
    learning_rate = 0.001
    num_iterations = 1000
    m,c = gradient_descent(points, learning_rate, num_iterations)
    return m,c


In [393]:
m,c=run()

In [394]:
np.around(m, decimals=100)

array([-0.71780834,  0.55595632, -0.09389334,  1.417138  , -0.46624404,
        3.98147951,  0.50962767, -0.55342928,  0.85458506,  0.07895533,
       -1.49892369,  0.6743183 , -3.03189895])

In [395]:
c

2.8168449057579403

In [396]:
test_data = np.loadtxt("_test_boston_x_test.csv",delimiter=",")

In [397]:
test_data

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [398]:
test_data.shape

(127, 13)

In [399]:
predictions = m*test_data + c

In [400]:
predictions.shape

(127, 13)

In [401]:
result =[]

In [402]:
for i in range(127):
    sum1 = 0
    for j in range(13):
        sum1 = sum1 + predictions[i][j]
    result.append(sum1)    

In [403]:
df["13"]

0      37.9
1      21.4
2      12.7
3      19.9
4      22.5
       ... 
374    50.0
375    14.3
376    20.8
377    22.6
378    50.0
Name: 13, Length: 379, dtype: float64

In [404]:
df.describe()

0           1           2           3           4           5  \
count  379.000000  379.000000  379.000000  379.000000  379.000000  379.000000   
mean     0.019628    0.002455    0.036170    0.028955    0.028775    0.032202   
std      1.067490    1.000813    1.017497    1.048995    0.999656    1.001174   
min     -0.417713   -0.487722   -1.516987   -0.272599   -1.465882   -3.880249   
25%     -0.408171   -0.487722   -0.867691   -0.272599   -0.878475   -0.571480   
50%     -0.383729   -0.487722   -0.180458   -0.272599   -0.144217   -0.103479   
75%      0.055208    0.156071    1.015999   -0.272599    0.628913    0.529069   
max      9.941735    3.804234    2.422565    3.668398    2.732346    3.555044   

                6           7           8           9          10          11  \
count  379.000000  379.000000  379.000000  379.000000  379.000000  379.000000   
mean     0.038395   -0.001288    0.043307    0.043786    0.019218   -0.015785   
std      0.985209    1.027803    1.016265    1.019974    1.000296    1.015797   
min     -2.335437   -1.267069   -0.982843   -1.313990   -2.707379   -3.883072   
25%     -0.768994   -0.829872   -0.637962   -0.755697   -0.488039    0.197588   
50%      0.338718   -0.329213   -0.523001   -0.440915    0.297977    0.374827   
75%      0.911243    0.674172    1.661245    1.530926    0.806576    0.429868   
max      1.117494    3.960518    1.661245    1.798194    1.638828    0.441052   

               12          13  
count  379.000000  379.000000  
mean     0.018418   22.609499  
std      1.015377    9.389647  
min     -1.531127    5.000000  
25%     -0.828856   16.700000  
50%     -0.161629   21.100000  
75%      0.647173   25.750000  
max      3.409999   50.000000

In [405]:
np.array(result)

array([24.44116397, 41.78028422, 34.9326852 , 36.64173574, 33.90251893,
       18.32668268, 40.8562819 , 35.76109731, 31.64372347, 34.48197368,
       37.31045677, 32.21136074, 34.00476255, 35.55080693, 60.50201662,
       36.90651417, 36.28791548, 39.06285671, 33.43408115, 44.1297092 ,
       36.68051294, 36.70056733, 46.23271636, 49.40930554, 46.37642711,
       29.32513761, 33.37975168, 43.9628969 , 39.59635581, 48.50464194,
       31.75857574, 37.5436174 , 37.13915323, 38.73784858, 31.33522653,
       40.46900016, 38.31327455, 33.99975976, 37.61317388, 27.01420345,
       18.98650793, 40.69908582, 42.48838143, 35.65349415, 35.2275537 ,
       16.22837778, 54.95921663, 39.44915778, 45.96595804, 33.89939597,
       32.29818689, 53.10322775, 34.69123811, 32.67434096, 30.93779031,
       33.90454949, 31.7896174 , 34.34645253, 28.15867521, 33.43470747,
       29.78135801, 41.83587428, 36.54456035, 38.29006783, 31.48017433,
       29.38386032, 47.1472445 , 33.72748183, 40.34469794, 36.99

In [391]:
np.array(result).shape

(127,)

In [408]:
pd1 = pd.DataFrame(result)

In [409]:
pd1.head()

0
0  24.441164
1  41.780284
2  34.932685
3  36.641736
4  33.902519

In [411]:
pd1.to_csv("prediction_Gradient_descent.csv")